baseURL = 'https://nanajaem1706.github.io'
defaultContentLanguage = 'id' 
languageCode = 'id'
title = 'SMPIT Nururrahman'
paginate = 4

[params]
    day = '2'
    monthYear = 'Jan 2006'
    time = '00:00'
    dateFormat = '2 January, 2006'
    shortDateFormat = '2 Jan, 2006'
    News = 'Team IT NR Masih bekerja Keras Terus berinovasi untuk menunjang Proses belajar mengajar di SMPIT Nururrahman, Nantikan Segera Launching Perpustakaan Digital .....'

[taxonomies]
    category = 'categories'
    author = 'authors'